### ISSUE TITLE
uranium

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#11]
![Uranium](https://user-images.githubusercontent.com/65222498/85943078-ca0d2400-b981-11ea-8c54-5e53118ccc5d.png)
can you add this please?

**Comment by ghost** [comment]
i am thinking off adding a bioharzard sign/block if it ok.

**Comment by ghost** [comment]
*of

**Comment by kettle-7** [comment]
Hi, sorry it's been 3 weeks since you posted this. Could you please upload the texture [here](https://github.com/Kettle3D/Kettle3D/upload/C%23/game/Assets/textures)? I should be able to add it in then.

**Comment by ghost** [comment]
Github says no becuase 
                       "Uploads are disabled.
File uploads require push access to this repository."

**Comment by ghost** [comment]
I'd like to say yes but...
Github says no becuase
"Uploads are disabled.
File uploads require push access to this repository."

**Comment by ghost** [comment]
Github says no becuase
"Uploads are disabled.
File uploads require push access to this repository."

**Comment by ghost** [comment]
YES TINNED MEAT
Github says no becuase
"Uploads are disabled.
File uploads require push access to this repository."

**Comment by kettle-7** [comment]
Okay, sorry. I'll try downloading the image. By the way, there's a new
update that saves your building in a file so you can use it again. I should
have your new biohazard block added to the game soon.

**Comment by ghost** [comment]
OK, no worries. (The bioharzard sign is still in progress as it is kind of hard to make is a 64x64 image )

**Comment by ghost** [comment]
*in a 64x64 image

**Comment by kettle-7** [comment]
Kettle3D has passed ten thousand lines of code!

**Comment by ghost** [comment]
WOHOOO!!!!!!!

**Comment by kettle-7** [comment]
Your blocks have been added. Thank you for your help.
