### ISSUE TITLE
New Block(s)

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#12]
I made a new wood log texture (I tried, I really did, the spiral is way too hard to make) and the bioharzard sign is finished (Also I realized it's actually a nuclear sign because i've been calling it the wrong name but...)
Pleaz add them to the game PLEAZZZZZZZZZZZZ
Tree top and bottom
![Tree top](https://user-images.githubusercontent.com/65222498/87849875-31464480-c940-11ea-9683-45db119e6cf7.png)
wood sides
![Wood](https://user-images.githubusercontent.com/65222498/87849878-33100800-c940-11ea-913e-b1899973f0eb.png)
Nuclear block generic (is that what you call it?)
![Nuclear symbol](https://user-images.githubusercontent.com/65222498/87849879-360af880-c940-11ea-9953-44259562f665.png)
Also you should expand the island and little bit bigger so... YOU CAN'T BEAT THE GAME SO EASILY. Definetly would make it harder if it a 200x200 island (he'll have to destory 20000 blocks HA try beating the game now)

**Comment by ghost** [comment]
Also i said he'll because i don't want to write he/she/(it)'ll

**Comment by ghost** [comment]
Personally i think wood side is quite good...

**Comment by kettle-7** [comment]
Hey,

When you say he you probably mean @orionisamazing, right?

**Comment by kettle-7** [comment]
Also, there is a template for block suggestions, I'll probably need to change the link on the website.

**Comment by ghost** [comment]
wow you here?

**Comment by ghost** [comment]
yes but @orionisamazing is not amazing

**Comment by kettle-7** [comment]
Hey, seeing as you have made a lot of textures, would you like me to add you as a collaborator? For Kettle3D, I mean.

**Comment by kettle-7** [comment]
https://github.com/Kettle3D/Kettle3D/invitations

**Comment by kettle-7** [comment]
Hi,

In order to add new blocks I'm going to have to make some modifications to the code that saves and loads the level, there's really no way around it, so it might take a while.

**Comment by kettle-7** [comment]
Have a look at [this](https://github.com/Kettle3D/Kettle3D/blob/C%23/game/Assets/Scripts/Game.cs)!

**Comment by kettle-7** [comment]
Okay, I've added your new blocks in, I'm just uploading the update package to GitHub. If you get the update, please make sure not to play on any existing levels because they will get corrupted.

**Comment by ghost** [comment]
Thanks for the invite...
Also i don't understand the code... you know : https://github.com/Kettle3D/Kettle3D/blob/C%23/game/Assets/Scripts/Game.cs
can you explain what you did?

**Comment by kettle-7** [comment]
Your blocks have been added. Thank you for your help.

**Comment by kettle-7** [comment]
So, about the code, everything that's after a '//' gets ignored and is called a comment, so I'll put some comments in explaining what everything does.

**Comment by NotJeb** [comment]
whaaaat, why am i not collaborator.
I've made lots of blocks too

**Comment by kettle-7** [comment]
You can use the same link.
