### ISSUE TITLE
uqwehjhdgds

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#14]
I am planning to make a iron block, an sidice block, obian, clay and sandstone for kettle3d and also i got a really cool idea, you know how in minecraft there's netherrack, acient debris and endstone and stuff, and they are just imaginary blocks. So what if we made some of or own blocks for kettle3d that doesn't exist in real life. (that would really make kettle3d diferrrent from minecraft)

**Comment by ghost** [comment]
*ice block
don't know what happend to my typing

**Comment by kettle-7** [comment]
I'm trying to not make this look like Minecraft, hence why I added your Oven block. In the future, could you please give your issue a better name?
