### ISSUE TITLE
Something has gone wrong. Please help!!!

### ISSUE THREAD

**Issue by NotJeb** [Kettle3D/Kettle3D#19]
This isn't meant to happen. What's going on???
==============================================

The Problem:
------------
This layout is very annoying becuse it asks the same thing like 10 times in 5 different ways

This layout is very annoying becuse it asks the same thing like 10 times in 5 different ways
What happened
-------------
I got annoyed at this layout becuase it is very annoying becuse it asks the same thing like 10 times in 5 different ways

I got annoyed at this layout becuase it is very annoying becuse it asks the same thing like 10 times in 5 different ways
What should've happened
-----------------------

It would say the question ONCE
More info
---------
WHY
### Platform

AGAIN. THE SAME QUESTION TWICE
- [ ] MacOS 
- [x] Windows 
- [ ] ChromeOS 
- [ ] Linux 
- [ ] Other 

### Kettle3D Version

- [ ] When I open Kettle3D, I see a black screen saying 'Made with Unity'
- [ ] When I open Kettle3D, I see a picture of a bridge over a river that was clearly drawn in MS Paint.
- [ ] When I open Kettle3D, after the 'Made with Unity' splash, I see a platform of grass.
- [ ] When I open Kettle3D, after the Unity splash, I see a gray piece of ground and a blue sky, but nothing in it.
- [ ] When I open Kettle3D, after the Unity splash, it asks me to pick a level.
- [ ] When I open Kettle3D, I see a window that says 'Kettle3D Launcher'
- [x] When I open Kettle3D, nothing happens. 

This is dumb

**Comment by NotJeb** [comment]
WHAT THE ****

**Comment by kettle-7** [comment]
Please do not spam. What exactly is your issue?

**Comment by NotJeb** [comment]
Your issue reporter layout is dumb.

**Comment by kettle-7** [comment]
You can change it if you like. You have edit access to the issue templates.
