### ISSUE TITLE
Not a bug but suggections.

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#6]
I made this block... Thought it might be useful... Please add it to the game.
![Bricks](https://user-images.githubusercontent.com/65222498/85114801-ba4d5b80-b26e-11ea-994e-f4ca662af770.png)

**Comment by kettle-7** [comment]
Thank you @CYBORG123456789. Your help is much appreciated.

**Comment by ghost** [comment]
no problem
