### ISSUE TITLE
I don't think you should remove walking through stuff

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#7]
I don't think you should remove walking through stuff becuase shouldn't the player be this really cool god that has unlimited everything and could fly, has infinite health and never dies? So why not add walk through walls to the list? Pleazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by ghost** [comment]
DON"T REMOVE IT

**Comment by kettle-7** [comment]
Hi @CYBORG123456789.

I might remove this eventually - @Miner888 told me I should, but for the moment I can't figure out how to.
