### ISSUE TITLE
BUG!!!!!!!!!!!!! URGENT!!!

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#8]
I was fiddleing around with the blocks and i found this:
![Screenshot (116)](https://user-images.githubusercontent.com/65222498/85197798-8a1dbf80-b337-11ea-915c-82088da707b1.png)

**Comment by ghost** [comment]
The ultimate white brick

**Comment by ghost** [comment]
also I don't think the block crumbleing thing is working (or maybe you haven't added it
![Screenshot (117)](https://user-images.githubusercontent.com/65222498/85197923-80e12280-b338-11ea-88d4-fce632650ed4.png)
)

**Comment by kettle-7** [comment]
Hi @CYBORG123456789, I haven't added this feature yet. I'll let you know when I have.
