### ISSUE TITLE
NEW BLOCKS (MAYBE YOU DON"T WANT THEM)

### ISSUE THREAD

**Issue by ghost** [Kettle3D/Kettle3D#9]
the oven block
![Oven block](https://user-images.githubusercontent.com/65222498/85220432-7b024480-b3ff-11ea-9664-d3829101cf03.png)
![oven sides and bottom](https://user-images.githubusercontent.com/65222498/85220434-7c337180-b3ff-11ea-8959-33748d8fea78.png)
![oven tp](https://user-images.githubusercontent.com/65222498/85220435-7ccc0800-b3ff-11ea-80c5-67f7f5e03436.png)
the stone brick
![Bricks](https://user-images.githubusercontent.com/65222498/85220655-6de65500-b401-11ea-9ada-ac75c7853cab.png)
snow block
![snow block](https://user-images.githubusercontent.com/65222498/85220840-f44f6680-b402-11ea-9d9f-32c5ebea2395.png)
sand block
![sand block](https://user-images.githubusercontent.com/65222498/85220945-bacb2b00-b403-11ea-81d0-a59f69866073.png)

**Comment by ghost** [comment]
QWERTYUIOP PLEAZ ADD THEM PLEAZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

**Comment by ghost** [comment]
also the first one of the oven blocks is front, then top, then sides and bottom

**Comment by CYBORG123456789** [comment]
*blocks

**Comment by kettle-7** [comment]
Hi, I'm just downloading them now. I should have them ready by tommorrow.

**Comment by kettle-7** [comment]
Hi, I just added the Oven.  
![Oven](https://raw.githubusercontent.com/Kettle3D/Kettle3D/C%23/assets/an%20oven.PNG)

**Comment by ghost** [comment]
NICEEEEEEE

**Comment by kettle-7** [comment]
I've added all of your blocks now.
![Some new Kettle3D blocks](https://raw.githubusercontent.com/Kettle3D/Kettle3D/C%23/assets/an%20oven.PNG)
